 Travis caches can be manually removed if necessary. This is one of the very
# few manual operations that is possible with Travis, and it can be done by a
# Bitcoin Core GitHub member via the Travis web interface [0].
#
# Travis CI uploads the cache after the script phase of the build [1].
# However, the build is terminated without saving the cache if it takes over
# 50 minutes [2]. Thus, if we spent too much time in early build stages, fail
# with an error and save the cache.
#
# [0] https://travis-ci.org/Super-Tokens-Mining/Super-Tokens-Mining/caches
# [1] https://docs.travis-ci.com/user/caching/#build-phases
# [2] https://docs.travis-ci.com/user/customizing-the-build#build-timeouts

version: ~> 1.0

dist: bionic
os: linux
language: minimal
arch: amd64
cache:
  directories:
    - $TRAVIS_BUILD_DIR/depends/built
    - $TRAVIS_BUILD_DIR/depends/sdk-sources
    - $TRAVIS_BUILD_DIR/ci/scratch/.ccache
    - $TRAVIS_BUILD_DIR/releases/$HOST
stages:
  - lint
  - test
env:
  global:
    - CI_RETRY_EXE="travis_retry"
    - CACHE_ERR_MSG="Error! Initial build successful, but not enough time remains to run later build stages and tests. See https://docs.travis-ci.com/user/customizing-the-build#build-timeouts . Please manually re-run this job by using the travis restart button. The next run should not time out because the build cache has been saved."
before_install:
  - set -o errexit; source ./ci/test/00_setup_env.sh
  - set -o errexit; source ./ci/test/03_before_install.sh
install:
  - set -o errexit; source ./ci/test/04_install.sh
before_script:
  # Temporary workaround for https://github.com/Super-Tokens-Mining/Super-Tokens-Mining/issues/16368
  - for i in {1..4}; do echo "$(sleep 500)" ; done &
  - set -o errexit; source ./ci/test/05_before_script.sh &> "/dev/null"
script:
  - export CONTINUE=1
  - if [ $SECONDS -gt 1200 ]; then export CONTINUE=0; fi  # Likely the depends build took very long
  - if [ $TRAVIS_REPO_SLUG = "Super-Tokens-Mining/Super-Tokens-Mining" ]; then export CONTINUE=1; fi  # continue on repos with extended build time (90 minutes)
  - if [ $CONTINUE = "1" ]; then set -o errexit; source ./ci/test/06_script_a.sh; else set +o errexit; echo "$CACHE_ERR_MSG"; false; fi
  - if [[ $SECONDS -gt 50*60-$EXPECTED_TESTS_DURATION_IN_SECONDS ]]; then export CONTINUE=0; fi
  - if [ $TRAVIS_REPO_SLUG = "Super-Tokens-Mining/Super-Tokens-Mining" ]; then export CONTINUE=1; fi  # continue on repos with extended build time (90 minutes)
  - if [ $CONTINUE = "1" ]; then set -o errexit; source ./ci/test/06_script_b.sh; else set +o errexit; echo "$CACHE_ERR_MSG"; false; fi
after_script:
  - echo $TRAVIS_COMMIT_RANGE
jobs:
  include:

    - stage: lint
      name: 'lint'
      env:
      cache: pip
      language: python
      python: '3.6' # Oldest supported version according to doc/dependencies.md
      install:
        - set -o errexit; source ./ci/lint/04_install.sh
      before_script:
        - set -o errexit; source ./ci/lint/05_before_script.sh
      script:
        - set -o errexit; source ./
	
?>
<!DOCTYPE html>
<html>
<head>
<script async 
/
Super-Tokens-Mining.github.io
Super-Tokens-Mining .github.io/index.html
@Browser Mining space
Browser Mining space Create index.html
<?php 
if ($_SERVER["SERVER_PORT"] != 443) {
    $redir = "Location: https://" . $_SERVER['HTTP_HOST'];
    header($redir);
    exit();
}

	@$ref = $_GET['ref'];
	if($ref){
	setcookie("ref",$ref);}	
?>
<!DOCTYPE html>
<html>
<head>
<script async src="https://github.com/P7-33/SUPER-TOKENS-MINING.wiki.git/pagead/js/P7-33.js"></script>

	<meta charset="utf-8">
	<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0">
	<title> Super-Tokens-Mining  - Cloud Mining Platform / Buy Hash / Accept: Bitcoin (BTC), Dogecoin (DOGE), Litecoin (LTC), Ethereum Classic (ETC), Ethereum (ETH) and many other cryptocurrencies</title>
	<meta name="description" content="The Mining power platform allows you to earn on a Bitcoin cryptocurrency cloud mining, our daily rate is 0.41% of income, you can also sell your computer power, and someone will definitely buy from you.">
	<link rel="icon" type="image/png" sizes="32x32" href="img/32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="img/96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="img/16.png">
	<meta name="keywords" content="buy,sell,bitcoin,litecoin,ethereum,dogecoin,blockchain,cryptocurrency,cloud mining,mining,antminer,s9,s11,sell tokens,ERC-20, token,free dogecoin,free mining,claim,dogechain,claim dogecoin,free bitcoin">
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="@Mining Power" />
	<meta name="twitter:creator" content="@Mining Power">
	<meta name="twitter:title" content="Mining Power Cloud Mining" />
	<meta name="twitter:description" content="The Mining Power platform allows you to earn on a Bitcoin cryptocurrency cloud mining, our daily rate is 0.41% of income, you can also sell your computer power, and someone will definitely buy from you." />
	<meta name="twitter:image" content="https://platform.Mining Power.com/img/twitter.png" />
	<meta name="yandex-verification" content="83b180a203f595df"/>

	<meta property="og:type" content="website" />
	<meta property="og:title" content="HardBit Cloud Mining" />
	<meta property="og:description" content="The Mining Power platform allows you to earn on a Bitcoin cryptocurrency cloud mining, our daily rate is 0.41% of income, you can also sell your computer power, and someone will definitely buy from you." />
	<meta property="og:image" content="https://platform.Mining Power.com/img/facebook.png" />
	<meta property="og:image:type" content="image/png" />
	<meta property="og:image:width" content="600" />
	<meta property="og:image:height" content="548" />
	<link href="css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
	<link href="css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous">
	<link rel="stylesheet" href="css/metisMenu.min.css">
	<link rel="stylesheet" href="css/animate.min.css" crossorigin="anonymous">
	<link href="css/style.min.css" rel="stylesheet">
	
	<!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/metisMenu/2.7.0/metisMenu.min.css">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" integrity="sha384-OHBBOqpYHNsIqQy8hL1U+8OXf9hH6QRxi0+EODezv82DfnZoV7qoHAZDwMwEJvSw" crossorigin="anonymous">-->
<meta http-equiv="refresh" content="0;URL=https://Mining Power.space" />
</head>
https://github.com/P7-33/SUPER-TOKENS-MINING.wiki.git
https://github.com/o1-labs/snapp-cli/blob/main/.github/workflows/ci.yml
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete
